# Add configuration values here, as shown below.

NAME: 'NAME'
SECRET_KEY_BASE: 'SECRET_KEY_BASE'
RAILS_MAX_THREADS: 'RAILS_MAX_THREADS'
development:
  POSTGRES_USERNAME: 'POSTGRES_USERNAME'
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD'
  HOST: 'HOST'
  FRONTEND: 'FRONTEND'
  FRONTEND_REDIRECTION_URL: 'FRONTEND_REDIRECTION_URL'
  MAILER_ADDRESS: 'MAILER_ADDRESS'
  MAILER_DOMAIN: 'MAILER_DOMAIN'
  MAILER_USER_NAME: 'DEVELOPMENT_MAILER_USER_NAME'
  MAILER_PASSWORD: 'DEVELOPMENT_MAILER_PASSWORD'
  MAILER_HOST: 'DEVELOPMENT_MAILER_HOST'
  
production:
  POSTGRES_USERNAME: 'POSTGRES_USERNAME'
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD'
  HOST: 'HOST'
  FRONTEND: 'FRONTEND'
  FRONTEND_REDIRECTION_URL: 'FRONTEND_REDIRECTION_URL'
  MAILER_ADDRESS: 'MAILER_ADDRESS'
  MAILER_DOMAIN: 'MAILER_DOMAIN'
  MAILER_USER_NAME: 'DEVELOPMENT_MAILER_USER_NAME'
  MAILER_PASSWORD: 'DEVELOPMENT_MAILER_PASSWORD'
  MAILER_HOST: 'DEVELOPMENT_MAILER_HOST'
  