# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f7aae4b12b189ee351687ad7b11a0eb6a28f86d177bc597be89cdc19c95fbd89ea2c535fc4d112660b7ca09a693d0a690e17a02b74267c70b2fcaf7f9ce3a3d

test:
  secret_key_base: a69f2b44f9874aeccda795954eebc7e0223b5dc80f798f5583e6e9ce79f23bab92408ad3259b1791337db46c44c6236f886ec1c7ff84af15f9b7a1aeb71303d4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
